[package]
name = "skclient"
version = "0.1.0"
authors = ["Hugo Dutka <contact@hugodutka.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
crossbeam = "0.7"
lazy_static = "1.4.0"
adorn = "0.3.0"
